import dependency from "./dependency.js";
export const d3 = dependency("d3", "6.7.0", "dist/d3.min.js");
export const d3Dsv = dependency("d3-dsv", "2.0.0", "dist/d3-dsv.min.js");
export const inputs = dependency("@observablehq/inputs", "0.8.0", "dist/inputs.umd.min.js");
export const plot = dependency("@observablehq/plot", "0.1.0", "dist/plot.umd.min.js");
export const graphviz = dependency("@observablehq/graphviz", "0.2.1", "dist/graphviz.min.js");
export const highlight = dependency("@observablehq/highlight.js", "2.0.0", "highlight.min.js");
export const katex = dependency("@observablehq/katex", "0.11.1", "dist/katex.min.js");
export const lodash = dependency("lodash", "4.17.21", "lodash.min.js");
export const htl = dependency("htl", "0.2.5", "dist/htl.min.js");
export const marked = dependency("marked", "0.3.12", "marked.min.js");
export const sql = dependency("sql.js", "1.5.0", "dist/sql-wasm.js");
export const vega = dependency("vega", "5.20.2", "build/vega.min.js");
export const vegalite = dependency("vega-lite", "5.1.0", "build/vega-lite.min.js");
export const vegaliteApi = dependency("vega-lite-api", "5.0.0", "build/vega-lite-api.min.js");
export const arrow = dependency("apache-arrow", "4.0.1", "Arrow.es2015.min.js");
export const topojson = dependency("topojson-client", "3.1.0", "dist/topojson-client.min.js");
